/* GENERATED by scripts/ow-l6/build.mjs — do not edit by hand.
   Source of truth: scripts/ow-l6/data/unit-<n>.mjs */
import type { Lesson } from "./types";
import l6u1openerTeacher from "../../content/subjects/english/courses/our-world/level-6/unit-1/lessons/opener.teacher.json";
import l6u1openerLearner from "../../content/subjects/english/courses/our-world/level-6/unit-1/lessons/opener.learner.json";
import l6u1vocab1Teacher from "../../content/subjects/english/courses/our-world/level-6/unit-1/lessons/vocab1.teacher.json";
import l6u1vocab1Learner from "../../content/subjects/english/courses/our-world/level-6/unit-1/lessons/vocab1.learner.json";
import l6u1songTeacher from "../../content/subjects/english/courses/our-world/level-6/unit-1/lessons/song.teacher.json";
import l6u1songLearner from "../../content/subjects/english/courses/our-world/level-6/unit-1/lessons/song.learner.json";
import l6u1grammar1Teacher from "../../content/subjects/english/courses/our-world/level-6/unit-1/lessons/grammar1.teacher.json";
import l6u1grammar1Learner from "../../content/subjects/english/courses/our-world/level-6/unit-1/lessons/grammar1.learner.json";
import l6u1vocab2Teacher from "../../content/subjects/english/courses/our-world/level-6/unit-1/lessons/vocab2.teacher.json";
import l6u1vocab2Learner from "../../content/subjects/english/courses/our-world/level-6/unit-1/lessons/vocab2.learner.json";
import l6u1grammar2Teacher from "../../content/subjects/english/courses/our-world/level-6/unit-1/lessons/grammar2.teacher.json";
import l6u1grammar2Learner from "../../content/subjects/english/courses/our-world/level-6/unit-1/lessons/grammar2.learner.json";
import l6u1readingTeacher from "../../content/subjects/english/courses/our-world/level-6/unit-1/lessons/reading.teacher.json";
import l6u1readingLearner from "../../content/subjects/english/courses/our-world/level-6/unit-1/lessons/reading.learner.json";
import l6u1writingTeacher from "../../content/subjects/english/courses/our-world/level-6/unit-1/lessons/writing.teacher.json";
import l6u1writingLearner from "../../content/subjects/english/courses/our-world/level-6/unit-1/lessons/writing.learner.json";

export const level6Lessons: Lesson[] = [
  l6u1openerTeacher as Lesson,
  l6u1openerLearner as Lesson,
  l6u1vocab1Teacher as Lesson,
  l6u1vocab1Learner as Lesson,
  l6u1songTeacher as Lesson,
  l6u1songLearner as Lesson,
  l6u1grammar1Teacher as Lesson,
  l6u1grammar1Learner as Lesson,
  l6u1vocab2Teacher as Lesson,
  l6u1vocab2Learner as Lesson,
  l6u1grammar2Teacher as Lesson,
  l6u1grammar2Learner as Lesson,
  l6u1readingTeacher as Lesson,
  l6u1readingLearner as Lesson,
  l6u1writingTeacher as Lesson,
  l6u1writingLearner as Lesson,
];
