/* GENERATED by scripts/ow-l6/build.mjs — do not edit by hand.
   Source of truth: scripts/ow-l6/data/unit-<n>.mjs */
import type { Lesson } from "./types";
import l6u1openerTeacher from "../../content/subjects/english/courses/our-world/level-6/unit-1/lessons/opener.teacher.json";
import l6u1openerLearner from "../../content/subjects/english/courses/our-world/level-6/unit-1/lessons/opener.learner.json";
import l6u1vocab1Teacher from "../../content/subjects/english/courses/our-world/level-6/unit-1/lessons/vocab1.teacher.json";
import l6u1vocab1Learner from "../../content/subjects/english/courses/our-world/level-6/unit-1/lessons/vocab1.learner.json";
import l6u1songTeacher from "../../content/subjects/english/courses/our-world/level-6/unit-1/lessons/song.teacher.json";
import l6u1songLearner from "../../content/subjects/english/courses/our-world/level-6/unit-1/lessons/song.learner.json";
import l6u1grammar1Teacher from "../../content/subjects/english/courses/our-world/level-6/unit-1/lessons/grammar1.teacher.json";
import l6u1grammar1Learner from "../../content/subjects/english/courses/our-world/level-6/unit-1/lessons/grammar1.learner.json";
import l6u1vocab2Teacher from "../../content/subjects/english/courses/our-world/level-6/unit-1/lessons/vocab2.teacher.json";
import l6u1vocab2Learner from "../../content/subjects/english/courses/our-world/level-6/unit-1/lessons/vocab2.learner.json";
import l6u1grammar2Teacher from "../../content/subjects/english/courses/our-world/level-6/unit-1/lessons/grammar2.teacher.json";
import l6u1grammar2Learner from "../../content/subjects/english/courses/our-world/level-6/unit-1/lessons/grammar2.learner.json";
import l6u1readingTeacher from "../../content/subjects/english/courses/our-world/level-6/unit-1/lessons/reading.teacher.json";
import l6u1readingLearner from "../../content/subjects/english/courses/our-world/level-6/unit-1/lessons/reading.learner.json";
import l6u1writingTeacher from "../../content/subjects/english/courses/our-world/level-6/unit-1/lessons/writing.teacher.json";
import l6u1writingLearner from "../../content/subjects/english/courses/our-world/level-6/unit-1/lessons/writing.learner.json";
import l6u2openerTeacher from "../../content/subjects/english/courses/our-world/level-6/unit-2/lessons/opener.teacher.json";
import l6u2openerLearner from "../../content/subjects/english/courses/our-world/level-6/unit-2/lessons/opener.learner.json";
import l6u2vocab1Teacher from "../../content/subjects/english/courses/our-world/level-6/unit-2/lessons/vocab1.teacher.json";
import l6u2vocab1Learner from "../../content/subjects/english/courses/our-world/level-6/unit-2/lessons/vocab1.learner.json";
import l6u2songTeacher from "../../content/subjects/english/courses/our-world/level-6/unit-2/lessons/song.teacher.json";
import l6u2songLearner from "../../content/subjects/english/courses/our-world/level-6/unit-2/lessons/song.learner.json";
import l6u2grammar1Teacher from "../../content/subjects/english/courses/our-world/level-6/unit-2/lessons/grammar1.teacher.json";
import l6u2grammar1Learner from "../../content/subjects/english/courses/our-world/level-6/unit-2/lessons/grammar1.learner.json";
import l6u2vocab2Teacher from "../../content/subjects/english/courses/our-world/level-6/unit-2/lessons/vocab2.teacher.json";
import l6u2vocab2Learner from "../../content/subjects/english/courses/our-world/level-6/unit-2/lessons/vocab2.learner.json";
import l6u2grammar2Teacher from "../../content/subjects/english/courses/our-world/level-6/unit-2/lessons/grammar2.teacher.json";
import l6u2grammar2Learner from "../../content/subjects/english/courses/our-world/level-6/unit-2/lessons/grammar2.learner.json";
import l6u2readingTeacher from "../../content/subjects/english/courses/our-world/level-6/unit-2/lessons/reading.teacher.json";
import l6u2readingLearner from "../../content/subjects/english/courses/our-world/level-6/unit-2/lessons/reading.learner.json";
import l6u2writingTeacher from "../../content/subjects/english/courses/our-world/level-6/unit-2/lessons/writing.teacher.json";
import l6u2writingLearner from "../../content/subjects/english/courses/our-world/level-6/unit-2/lessons/writing.learner.json";
import l6u3openerTeacher from "../../content/subjects/english/courses/our-world/level-6/unit-3/lessons/opener.teacher.json";
import l6u3openerLearner from "../../content/subjects/english/courses/our-world/level-6/unit-3/lessons/opener.learner.json";
import l6u3vocab1Teacher from "../../content/subjects/english/courses/our-world/level-6/unit-3/lessons/vocab1.teacher.json";
import l6u3vocab1Learner from "../../content/subjects/english/courses/our-world/level-6/unit-3/lessons/vocab1.learner.json";
import l6u3songTeacher from "../../content/subjects/english/courses/our-world/level-6/unit-3/lessons/song.teacher.json";
import l6u3songLearner from "../../content/subjects/english/courses/our-world/level-6/unit-3/lessons/song.learner.json";
import l6u3grammar1Teacher from "../../content/subjects/english/courses/our-world/level-6/unit-3/lessons/grammar1.teacher.json";
import l6u3grammar1Learner from "../../content/subjects/english/courses/our-world/level-6/unit-3/lessons/grammar1.learner.json";
import l6u3vocab2Teacher from "../../content/subjects/english/courses/our-world/level-6/unit-3/lessons/vocab2.teacher.json";
import l6u3vocab2Learner from "../../content/subjects/english/courses/our-world/level-6/unit-3/lessons/vocab2.learner.json";
import l6u3grammar2Teacher from "../../content/subjects/english/courses/our-world/level-6/unit-3/lessons/grammar2.teacher.json";
import l6u3grammar2Learner from "../../content/subjects/english/courses/our-world/level-6/unit-3/lessons/grammar2.learner.json";
import l6u3readingTeacher from "../../content/subjects/english/courses/our-world/level-6/unit-3/lessons/reading.teacher.json";
import l6u3readingLearner from "../../content/subjects/english/courses/our-world/level-6/unit-3/lessons/reading.learner.json";
import l6u3writingTeacher from "../../content/subjects/english/courses/our-world/level-6/unit-3/lessons/writing.teacher.json";
import l6u3writingLearner from "../../content/subjects/english/courses/our-world/level-6/unit-3/lessons/writing.learner.json";
import l6u4openerTeacher from "../../content/subjects/english/courses/our-world/level-6/unit-4/lessons/opener.teacher.json";
import l6u4openerLearner from "../../content/subjects/english/courses/our-world/level-6/unit-4/lessons/opener.learner.json";
import l6u4vocab1Teacher from "../../content/subjects/english/courses/our-world/level-6/unit-4/lessons/vocab1.teacher.json";
import l6u4vocab1Learner from "../../content/subjects/english/courses/our-world/level-6/unit-4/lessons/vocab1.learner.json";
import l6u4songTeacher from "../../content/subjects/english/courses/our-world/level-6/unit-4/lessons/song.teacher.json";
import l6u4songLearner from "../../content/subjects/english/courses/our-world/level-6/unit-4/lessons/song.learner.json";
import l6u4grammar1Teacher from "../../content/subjects/english/courses/our-world/level-6/unit-4/lessons/grammar1.teacher.json";
import l6u4grammar1Learner from "../../content/subjects/english/courses/our-world/level-6/unit-4/lessons/grammar1.learner.json";
import l6u4vocab2Teacher from "../../content/subjects/english/courses/our-world/level-6/unit-4/lessons/vocab2.teacher.json";
import l6u4vocab2Learner from "../../content/subjects/english/courses/our-world/level-6/unit-4/lessons/vocab2.learner.json";
import l6u4grammar2Teacher from "../../content/subjects/english/courses/our-world/level-6/unit-4/lessons/grammar2.teacher.json";
import l6u4grammar2Learner from "../../content/subjects/english/courses/our-world/level-6/unit-4/lessons/grammar2.learner.json";
import l6u4readingTeacher from "../../content/subjects/english/courses/our-world/level-6/unit-4/lessons/reading.teacher.json";
import l6u4readingLearner from "../../content/subjects/english/courses/our-world/level-6/unit-4/lessons/reading.learner.json";
import l6u4writingTeacher from "../../content/subjects/english/courses/our-world/level-6/unit-4/lessons/writing.teacher.json";
import l6u4writingLearner from "../../content/subjects/english/courses/our-world/level-6/unit-4/lessons/writing.learner.json";
import l6u5openerTeacher from "../../content/subjects/english/courses/our-world/level-6/unit-5/lessons/opener.teacher.json";
import l6u5openerLearner from "../../content/subjects/english/courses/our-world/level-6/unit-5/lessons/opener.learner.json";
import l6u5vocab1Teacher from "../../content/subjects/english/courses/our-world/level-6/unit-5/lessons/vocab1.teacher.json";
import l6u5vocab1Learner from "../../content/subjects/english/courses/our-world/level-6/unit-5/lessons/vocab1.learner.json";
import l6u5songTeacher from "../../content/subjects/english/courses/our-world/level-6/unit-5/lessons/song.teacher.json";
import l6u5songLearner from "../../content/subjects/english/courses/our-world/level-6/unit-5/lessons/song.learner.json";
import l6u5grammar1Teacher from "../../content/subjects/english/courses/our-world/level-6/unit-5/lessons/grammar1.teacher.json";
import l6u5grammar1Learner from "../../content/subjects/english/courses/our-world/level-6/unit-5/lessons/grammar1.learner.json";
import l6u5vocab2Teacher from "../../content/subjects/english/courses/our-world/level-6/unit-5/lessons/vocab2.teacher.json";
import l6u5vocab2Learner from "../../content/subjects/english/courses/our-world/level-6/unit-5/lessons/vocab2.learner.json";
import l6u5grammar2Teacher from "../../content/subjects/english/courses/our-world/level-6/unit-5/lessons/grammar2.teacher.json";
import l6u5grammar2Learner from "../../content/subjects/english/courses/our-world/level-6/unit-5/lessons/grammar2.learner.json";
import l6u5readingTeacher from "../../content/subjects/english/courses/our-world/level-6/unit-5/lessons/reading.teacher.json";
import l6u5readingLearner from "../../content/subjects/english/courses/our-world/level-6/unit-5/lessons/reading.learner.json";
import l6u5writingTeacher from "../../content/subjects/english/courses/our-world/level-6/unit-5/lessons/writing.teacher.json";
import l6u5writingLearner from "../../content/subjects/english/courses/our-world/level-6/unit-5/lessons/writing.learner.json";
import l6u6openerTeacher from "../../content/subjects/english/courses/our-world/level-6/unit-6/lessons/opener.teacher.json";
import l6u6openerLearner from "../../content/subjects/english/courses/our-world/level-6/unit-6/lessons/opener.learner.json";
import l6u6vocab1Teacher from "../../content/subjects/english/courses/our-world/level-6/unit-6/lessons/vocab1.teacher.json";
import l6u6vocab1Learner from "../../content/subjects/english/courses/our-world/level-6/unit-6/lessons/vocab1.learner.json";
import l6u6songTeacher from "../../content/subjects/english/courses/our-world/level-6/unit-6/lessons/song.teacher.json";
import l6u6songLearner from "../../content/subjects/english/courses/our-world/level-6/unit-6/lessons/song.learner.json";
import l6u6grammar1Teacher from "../../content/subjects/english/courses/our-world/level-6/unit-6/lessons/grammar1.teacher.json";
import l6u6grammar1Learner from "../../content/subjects/english/courses/our-world/level-6/unit-6/lessons/grammar1.learner.json";
import l6u6vocab2Teacher from "../../content/subjects/english/courses/our-world/level-6/unit-6/lessons/vocab2.teacher.json";
import l6u6vocab2Learner from "../../content/subjects/english/courses/our-world/level-6/unit-6/lessons/vocab2.learner.json";
import l6u6grammar2Teacher from "../../content/subjects/english/courses/our-world/level-6/unit-6/lessons/grammar2.teacher.json";
import l6u6grammar2Learner from "../../content/subjects/english/courses/our-world/level-6/unit-6/lessons/grammar2.learner.json";
import l6u6readingTeacher from "../../content/subjects/english/courses/our-world/level-6/unit-6/lessons/reading.teacher.json";
import l6u6readingLearner from "../../content/subjects/english/courses/our-world/level-6/unit-6/lessons/reading.learner.json";
import l6u6writingTeacher from "../../content/subjects/english/courses/our-world/level-6/unit-6/lessons/writing.teacher.json";
import l6u6writingLearner from "../../content/subjects/english/courses/our-world/level-6/unit-6/lessons/writing.learner.json";
import l6u7openerTeacher from "../../content/subjects/english/courses/our-world/level-6/unit-7/lessons/opener.teacher.json";
import l6u7openerLearner from "../../content/subjects/english/courses/our-world/level-6/unit-7/lessons/opener.learner.json";
import l6u7vocab1Teacher from "../../content/subjects/english/courses/our-world/level-6/unit-7/lessons/vocab1.teacher.json";
import l6u7vocab1Learner from "../../content/subjects/english/courses/our-world/level-6/unit-7/lessons/vocab1.learner.json";
import l6u7songTeacher from "../../content/subjects/english/courses/our-world/level-6/unit-7/lessons/song.teacher.json";
import l6u7songLearner from "../../content/subjects/english/courses/our-world/level-6/unit-7/lessons/song.learner.json";
import l6u7grammar1Teacher from "../../content/subjects/english/courses/our-world/level-6/unit-7/lessons/grammar1.teacher.json";
import l6u7grammar1Learner from "../../content/subjects/english/courses/our-world/level-6/unit-7/lessons/grammar1.learner.json";
import l6u7vocab2Teacher from "../../content/subjects/english/courses/our-world/level-6/unit-7/lessons/vocab2.teacher.json";
import l6u7vocab2Learner from "../../content/subjects/english/courses/our-world/level-6/unit-7/lessons/vocab2.learner.json";
import l6u7grammar2Teacher from "../../content/subjects/english/courses/our-world/level-6/unit-7/lessons/grammar2.teacher.json";
import l6u7grammar2Learner from "../../content/subjects/english/courses/our-world/level-6/unit-7/lessons/grammar2.learner.json";
import l6u7readingTeacher from "../../content/subjects/english/courses/our-world/level-6/unit-7/lessons/reading.teacher.json";
import l6u7readingLearner from "../../content/subjects/english/courses/our-world/level-6/unit-7/lessons/reading.learner.json";
import l6u7writingTeacher from "../../content/subjects/english/courses/our-world/level-6/unit-7/lessons/writing.teacher.json";
import l6u7writingLearner from "../../content/subjects/english/courses/our-world/level-6/unit-7/lessons/writing.learner.json";

export const level6Lessons: Lesson[] = [
  l6u1openerTeacher as Lesson,
  l6u1openerLearner as Lesson,
  l6u1vocab1Teacher as Lesson,
  l6u1vocab1Learner as Lesson,
  l6u1songTeacher as Lesson,
  l6u1songLearner as Lesson,
  l6u1grammar1Teacher as Lesson,
  l6u1grammar1Learner as Lesson,
  l6u1vocab2Teacher as Lesson,
  l6u1vocab2Learner as Lesson,
  l6u1grammar2Teacher as Lesson,
  l6u1grammar2Learner as Lesson,
  l6u1readingTeacher as Lesson,
  l6u1readingLearner as Lesson,
  l6u1writingTeacher as Lesson,
  l6u1writingLearner as Lesson,
  l6u2openerTeacher as Lesson,
  l6u2openerLearner as Lesson,
  l6u2vocab1Teacher as Lesson,
  l6u2vocab1Learner as Lesson,
  l6u2songTeacher as Lesson,
  l6u2songLearner as Lesson,
  l6u2grammar1Teacher as Lesson,
  l6u2grammar1Learner as Lesson,
  l6u2vocab2Teacher as Lesson,
  l6u2vocab2Learner as Lesson,
  l6u2grammar2Teacher as Lesson,
  l6u2grammar2Learner as Lesson,
  l6u2readingTeacher as Lesson,
  l6u2readingLearner as Lesson,
  l6u2writingTeacher as Lesson,
  l6u2writingLearner as Lesson,
  l6u3openerTeacher as Lesson,
  l6u3openerLearner as Lesson,
  l6u3vocab1Teacher as Lesson,
  l6u3vocab1Learner as Lesson,
  l6u3songTeacher as Lesson,
  l6u3songLearner as Lesson,
  l6u3grammar1Teacher as Lesson,
  l6u3grammar1Learner as Lesson,
  l6u3vocab2Teacher as Lesson,
  l6u3vocab2Learner as Lesson,
  l6u3grammar2Teacher as Lesson,
  l6u3grammar2Learner as Lesson,
  l6u3readingTeacher as Lesson,
  l6u3readingLearner as Lesson,
  l6u3writingTeacher as Lesson,
  l6u3writingLearner as Lesson,
  l6u4openerTeacher as Lesson,
  l6u4openerLearner as Lesson,
  l6u4vocab1Teacher as Lesson,
  l6u4vocab1Learner as Lesson,
  l6u4songTeacher as Lesson,
  l6u4songLearner as Lesson,
  l6u4grammar1Teacher as Lesson,
  l6u4grammar1Learner as Lesson,
  l6u4vocab2Teacher as Lesson,
  l6u4vocab2Learner as Lesson,
  l6u4grammar2Teacher as Lesson,
  l6u4grammar2Learner as Lesson,
  l6u4readingTeacher as Lesson,
  l6u4readingLearner as Lesson,
  l6u4writingTeacher as Lesson,
  l6u4writingLearner as Lesson,
  l6u5openerTeacher as Lesson,
  l6u5openerLearner as Lesson,
  l6u5vocab1Teacher as Lesson,
  l6u5vocab1Learner as Lesson,
  l6u5songTeacher as Lesson,
  l6u5songLearner as Lesson,
  l6u5grammar1Teacher as Lesson,
  l6u5grammar1Learner as Lesson,
  l6u5vocab2Teacher as Lesson,
  l6u5vocab2Learner as Lesson,
  l6u5grammar2Teacher as Lesson,
  l6u5grammar2Learner as Lesson,
  l6u5readingTeacher as Lesson,
  l6u5readingLearner as Lesson,
  l6u5writingTeacher as Lesson,
  l6u5writingLearner as Lesson,
  l6u6openerTeacher as Lesson,
  l6u6openerLearner as Lesson,
  l6u6vocab1Teacher as Lesson,
  l6u6vocab1Learner as Lesson,
  l6u6songTeacher as Lesson,
  l6u6songLearner as Lesson,
  l6u6grammar1Teacher as Lesson,
  l6u6grammar1Learner as Lesson,
  l6u6vocab2Teacher as Lesson,
  l6u6vocab2Learner as Lesson,
  l6u6grammar2Teacher as Lesson,
  l6u6grammar2Learner as Lesson,
  l6u6readingTeacher as Lesson,
  l6u6readingLearner as Lesson,
  l6u6writingTeacher as Lesson,
  l6u6writingLearner as Lesson,
  l6u7openerTeacher as Lesson,
  l6u7openerLearner as Lesson,
  l6u7vocab1Teacher as Lesson,
  l6u7vocab1Learner as Lesson,
  l6u7songTeacher as Lesson,
  l6u7songLearner as Lesson,
  l6u7grammar1Teacher as Lesson,
  l6u7grammar1Learner as Lesson,
  l6u7vocab2Teacher as Lesson,
  l6u7vocab2Learner as Lesson,
  l6u7grammar2Teacher as Lesson,
  l6u7grammar2Learner as Lesson,
  l6u7readingTeacher as Lesson,
  l6u7readingLearner as Lesson,
  l6u7writingTeacher as Lesson,
  l6u7writingLearner as Lesson,
];
