/* GENERATED by scripts/ow-l6/build.mjs — do not edit by hand.
   Source of truth: scripts/ow-l6/data/unit-<n>.mjs */
import l6u1Vocabulary from "../../content/subjects/english/courses/our-world/level-6/unit-1/vocabulary.json";
import l6u1Grammar from "../../content/subjects/english/courses/our-world/level-6/unit-1/grammar.json";

/* Every scanned Level 6 unit file, in unit order. reference.ts spreads these so
   Level 6 words and grammar points reach the merged reference layer, the source
   tree, and the vocabulary/grammar browse views without 18 more import lines. */
export const level6Vocabularies = [
  l6u1Vocabulary,
];

export const level6Grammars = [
  l6u1Grammar,
];

export const level6UnitTitles: Record<string, string> = Object.fromEntries(
  level6Vocabularies.map((unit) => [`${unit.level}-${unit.unit}`, unit.unitTitle])
);
